name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Deploys on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create gh-pages branch (if not exists)
        run: |
          git branch -M gh-pages  # Ensure we're pushing to the gh-pages branch
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Force commit an empty commit if nothing has changed
        run: |
          git add .
          git commit -m "Trigger GitHub Pages deploy" || echo "No changes to commit"
          git push --force origin gh-pages  # Force push to gh-pages branch for GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}